// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA2aYzTFY7KyDOrorzMrXCUUM_x8MCvBzI',
    appId: '1:184000393889:web:71fd4879b23cfe7b08b6e0',
    messagingSenderId: '184000393889',
    projectId: 'vehicle-tracker-61091',
    authDomain: 'vehicle-tracker-61091.firebaseapp.com',
    storageBucket: 'vehicle-tracker-61091.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCNWcpwwCl6K1rEAyafrZziWJONx_VFcLk',
    appId: '1:184000393889:android:2c1dd61ef4de81a508b6e0',
    messagingSenderId: '184000393889',
    projectId: 'vehicle-tracker-61091',
    storageBucket: 'vehicle-tracker-61091.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAqzDpt9MEFjxp35zRm-dPNP_DS4aENffs',
    appId: '1:184000393889:ios:2686c3d5f3623e8708b6e0',
    messagingSenderId: '184000393889',
    projectId: 'vehicle-tracker-61091',
    storageBucket: 'vehicle-tracker-61091.firebasestorage.app',
    iosBundleId: 'com.example.vehicleTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAqzDpt9MEFjxp35zRm-dPNP_DS4aENffs',
    appId: '1:184000393889:ios:2686c3d5f3623e8708b6e0',
    messagingSenderId: '184000393889',
    projectId: 'vehicle-tracker-61091',
    storageBucket: 'vehicle-tracker-61091.firebasestorage.app',
    iosBundleId: 'com.example.vehicleTracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA2aYzTFY7KyDOrorzMrXCUUM_x8MCvBzI',
    appId: '1:184000393889:web:00c68621f191c6b908b6e0',
    messagingSenderId: '184000393889',
    projectId: 'vehicle-tracker-61091',
    authDomain: 'vehicle-tracker-61091.firebaseapp.com',
    storageBucket: 'vehicle-tracker-61091.firebasestorage.app',
  );
}
